### ISSUE TITLE
Use timm feature forward

### ISSUE THREAD

**Issue by AlexanderNevarko** [nkb-tech/nkb-classification#9]
Use timm feature forward for more architectures compatibility.
[timm docs](https://huggingface.co/docs/timm/quickstart#use-a-pretrained-model-for-feature-extraction)
Be aware for transformer models

**Comment by viacheslavm21** [comment]
Backbone extraction is changed for models available in timm.
All other code is left unchanged.
Added a readme guide how to choose different backbone types.

**Comment by viacheslavm21** [comment]
Tested with convnext, resnet, vit and unicom

**Comment by viacheslavm21** [comment]
Done
